@echo off
title FAUST Backend ASR Service
cd %~dp0
echo FAUST Backend ASR Service Starting...
echo Activating conda environment 'faustbot'...
conda activate faustbot && python asr_api.py >log_asr.log 2>&1
echo Running ASR service...