@echo off
cd %~dp0
title FAUST Backend MAIN Service
echo FAUST Backend MAIN Service Starting...
echo Activating conda environment 'faustbot'...
conda activate faustbot && python backend-main.py --no-startup-chat
echo Running MAIN service...